version: "3.3"

services:
  nginx:
    build:
      context: .
      dockerfile: _docker/nginx.dockerfile
    ports:
      - 8090:80
    links:
      - fpm
    volumes:
      - ./:/var/www
  fpm:
    build:
      context: .
      dockerfile: _docker/fpm.dockerfile
    volumes:
      - ./:/var/www
    working_dir: /var/www
    links:
      - mysql

  mysql:
    platform: linux/arm64/v8
    image: mysql:8.0
    restart: always
    volumes:
      - ./tmp/db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=database
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci

  phpmyadmin:
    image: phpmyadmin
    restart: always
    environment:
      - PMA_ARBITRARY=1
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 6090:80
    depends_on:
      - mysql

volumes:
  data:
